name: Build

on: [push, pull_request]

jobs:
  build:
    name: SDK build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.16.0'

      - run: yarn install

      - run: yarn test

      - run: yarn coverage

      - run: yarn build

      - name: Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
